config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  namespace :admin do
    resources :subjects
    resources :exams
    resources :specialities
    root to: "exams#index"
  end
  namespace :api do
    resources :specialities, only: [:index]
    resources :subjects, only: [:index]
  end
  get "up" => "rails/health#show", as: :rails_health_check
  get 'locale/:locale', to: 'locale#switch', as: :switch_locale
end

app/models/exam.rb
class Exam < ApplicationRecord
  self.primary_key = :id
  validates :label, presence: true
  has_many :specialities, dependent: :destroy
end

app/controllers/admin/exams_controller.rb
module Admin
  class ExamsController < Admin::BaseController
    before_action :set_exam, only: %i[ edit update destroy ]

    # GET /exams or /exams.json
    def index
      @exams = Exam.all
    end

    # GET /exams/new
    def new
      @exam = Exam.new
    end

    # GET /exams/1/edit
    def edit
    end

    # POST /exams or /exams.json
    def create
      @exam = Exam.new(exam_params)

      respond_to do |format|
        if @exam.save
          format.html { redirect_to admin_exams_path, notice: "Exam was successfully created." }
          format.json { render json: @exam, status: :created }
        else
          format.html do
            @exams = Exam.all
            render :index, status: :unprocessable_entity
          end
          format.json { render json: { errors: @exam.errors }, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /exams/1 or /exams/1.json
    def update
      respond_to do |format|
        if @exam.update(exam_params)
          format.html { redirect_to admin_exams_path, notice: "Exam was successfully updated.", status: :see_other }
          format.json { render json: @exam, status: :ok }
        else
          format.html do
            @exams = Exam.all
            render :index, status: :unprocessable_entity
          end
          format.json { render json: { errors: @exam.errors }, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /exams/1 or /exams/1.json
    def destroy
      @exam.destroy!

      respond_to do |format|
        format.html { redirect_to admin_exams_path, notice: "Exam was successfully destroyed.", status: :see_other }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def exam_params
      params.require(:exam).permit(:label, :description)
    end
  end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/_form.html.erb
<%= form_with(model: exam) do |form| %>
  <% if exam.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

      <ul>
        <% exam.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :label, style: "display: block" %>
    <%= form.text_field :label %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/exams/edit.html.erb
<% content_for :title, "Editing exam" %>

<h1>Editing exam</h1>

<%= render "form", exam: @exam %>

<br>

<div>
  <%= link_to "Show this exam", @exam %> |
  <%= link_to "Back to exams", exams_path %>
</div>

app/views/exams/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Exams" %>

<h1>Exams</h1>

<div id="exams">
  <% @exams.each do |exam| %>
    <%= render exam %>
    <p>
      <%= link_to "Show this exam", exam %>
    </p>
  <% end %>
</div>

<%= link_to "New exam", new_exam_path %>

app/views/exams/new.html.erb
<% content_for :title, "New exam" %>

<h1>New exam</h1>

<%= render "form", exam: @exam %>

<br>

<div>
  <%= link_to "Back to exams", exams_path %>
</div>