config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  namespace :admin do
    resources :subjects
    resources :exams
    resources :specialities
    root to: "exams#index"
  end
  namespace :api do
    resources :specialities, only: [:index]
    resources :subjects, only: [:index]
  end
  get "up" => "rails/health#show", as: :rails_health_check
  get 'locale/:locale', to: 'locale#switch', as: :switch_locale
end

app/views/layouts/_admin_nav.html.erb
<nav class="mb-3">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <%= link_to t('admin_nav.exams'), admin_exams_path, class: "nav-link #{admin_nav_active_class(:exams)}" %>
    </li>
    <li class="nav-item">
      <%= link_to t('admin_nav.specialities'), admin_specialities_path, class: "nav-link #{admin_nav_active_class(:specialities)}" %>
    </li>
    <li class="nav-item">
      <%= link_to t('admin_nav.subjects'), admin_subjects_path, class: "nav-link #{admin_nav_active_class(:subjects)}" %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">

    <title><%= content_for(:title) || "Prepa-Examen" %></title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Bootstrap CSS (CDN) should be loaded before your app styles so your overrides win %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css", rel: "stylesheet", crossorigin: "anonymous" %>

    <%# Includes application.css from app/assets/stylesheets %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
  <%= render "home/header" %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

    <% if @admin_area %>
      <div class="container-fluid my-4">
        <div class="row">
          <div class="col-12">
            <%= render "layouts/admin_nav" %>
          </div>
        </div>

        <div class="container my-4">
          <%= yield %>
        </div>
      </div>
    <% else %>
      <div class="container my-4">
        <%= yield %>
      </div>
    <% end %>
  </body>
</html>